In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [3]:
train_df = pd.read_csv(Path('../2019loans.csv'))
test_df = pd.read_csv(Path('../2020Q1loans.csv'))

In [4]:
train_df

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,354912,354912,19975.0,0.2565,801.09,RENT,28000.0,Not Verified,high_risk,n,...,100.0,16.7,0.0,0.0,50055.0,28192.0,18700.0,19055.0,N,N
12176,354944,354944,15000.0,0.1774,540.34,RENT,50000.0,Verified,high_risk,n,...,90.5,11.1,0.0,0.0,70324.0,57025.0,13300.0,54824.0,N,N
12177,354973,354973,3600.0,0.1862,131.28,RENT,60000.0,Not Verified,high_risk,n,...,100.0,0.0,0.0,0.0,83765.0,55156.0,14800.0,53065.0,N,N
12178,355002,355002,15000.0,0.0881,475.68,MORTGAGE,62000.0,Source Verified,high_risk,n,...,100.0,0.0,0.0,0.0,189930.0,23748.0,7000.0,32930.0,N,N
12179,355307,355307,15000.0,0.1774,540.34,RENT,54080.0,Not Verified,high_risk,n,...,90.0,100.0,0.0,0.0,48968.0,29786.0,2900.0,33968.0,N,N

In [5]:
test_df

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,67991,67991,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,25429,25429,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,38496,38496,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,19667,19667,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,37505,37505,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,77282,77282,30000.0,0.1240,673.42,RENT,140480.0,Source Verified,high_risk,n,...,100.0,28.6,0.0,0.0,159688.0,110873.0,48400.0,107388.0,N,N
4698,77291,77291,24000.0,0.0756,747.22,RENT,50000.0,Not Verified,high_risk,n,...,100.0,0.0,0.0,0.0,62375.0,18928.0,13300.0,30775.0,N,N
4699,77292,77292,10000.0,0.2305,387.36,RENT,33000.0,Verified,high_risk,n,...,100.0,0.0,0.0,0.0,43250.0,33022.0,8500.0,29550.0,N,N
4700,77297,77297,8000.0,0.1862,205.86,RENT,38000.0,Source Verified,high_risk,n,...,95.0,0.0,1.0,0.0,31357.0,19595.0,1500.0,9657.0,N,N
4701,77304,77304,30000.0,0.2055,1123.34,RENT,180000.0,Source Verified,high_risk,n,...,100.0,33.3,0.0,0.0,218686.0,209389.0,5600.0,209986.0,N,N

In [10]:
train_df.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'home_ownership', 'annual_inc', 'verification_status', 'loan_status',
       'pymnt_plan', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'policy_code', 'application_type',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'debt_settlement_flag'],
      dtype='object')

In [12]:
train_df["loan_status"].value_counts()

high_risk    6090
low_risk     6090
Name: loan_status, dtype: int64

In [13]:
# Convert categorical data to numeric and separate target feature for training data
train_df.info()

# Remove NA values, none found




# Use get_dummies()
X_train_df = pd.get_dummies(train_df.drop(columns=["loan_status"]))
X_train_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  12180 non-null  int64
 1   index                       12180 non-null  int64
 2   loan_amnt                   12180 non-null  float64
 3   int_rate                    12180 non-null  float64
 4   installment                 12180 non-null  float64
 5   home_ownership              12180 non-null  object
 6   annual_inc                  12180 non-null  float64
 7   verification_status         12180 non-null  object
 8   loan_status                 12180 non-null  object
 9   pymnt_plan                  12180 non-null  object
 10  dti                         12180 non-null  float64
 11  delinq_2yrs                 12180 non-null  float64
 12  inq_last_6mths              12180 non-null  float64
 13  open_acc                    12180 non-null  float64
 14  pub_rec                     12180 non-null  float64
 15  revol_bal                   12180 non-null  float64
 16  total_acc                   12180 non-null  float64
 17  initial_list_status         12180 non-null  object
 18  out_prncp                   12180 non-null  float64
 19  out_prncp_inv               12180 non-null  float64
 20  total_pymnt                 12180 non-null  float64
 21  total_pymnt_inv             12180 non-null  float64
 22  total_rec_prncp             12180 non-null  float64
 23  total_rec_int               12180 non-null  float64
 24  total_rec_late_fee          12180 non-null  float64
 25  recoveries                  12180 non-null  float64
 26  collection_recovery_fee     12180 non-null  float64
 27  last_pymnt_amnt             12180 non-null  float64
 28  collections_12_mths_ex_med  12180 non-null  float64
 29  policy_code                 12180 non-null  float64
 30  application_type            12180 non-null  object
 31  acc_now_delinq              12180 non-null  float64
 32  tot_coll_amt                12180 non-null  float64
 33  tot_cur_bal                 12180 non-null  float64
 34  open_acc_6m                 12180 non-null  float64
 35  open_act_il                 12180 non-null  float64
 36  open_il_12m                 12180 non-null  float64
 37  open_il_24m                 12180 non-null  float64
 38  mths_since_rcnt_il          12180 non-null  float64
 39  total_bal_il                12180 non-null  float64
 40  il_util                     12180 non-null  float64
 41  open_rv_12m                 12180 non-null  float64
 42  open_rv_24m                 12180 non-null  float64
 43  max_bal_bc                  12180 non-null  float64
 44  all_util                    12180 non-null  float64
 45  total_rev_hi_lim            12180 non-null  float64
 46  inq_fi                      12180 non-null  float64
 47  total_cu_tl                 12180 non-null  float64
 48  inq_last_12m                12180 non-null  float64
 49  acc_open_past_24mths        12180 non-null  float64
 50  avg_cur_bal                 12180 non-null  float64
 51  bc_open_to_buy              12180 non-null  float64
 52  bc_util                     12180 non-null  float64
 53  chargeoff_within_12_mths    12180 non-null  float64
 54  delinq_amnt                 12180 non-null  float64
 55  mo_sin_old_il_acct          12180 non-null  float64
 56  mo_sin_old_rev_tl_op        12180 non-null  float64
 57  mo_sin_rcnt_rev_tl_op       12180 non-null  float64
 58  mo_sin_rcnt_tl              12180 non-null  float64
 59  mort_acc                    12180 non-null  float64
 60  mths_since_recent_bc        12180 non-null  float64
 61  mths_since_recent_inq       12180 non-null  float64
 62  num_accts_ever_120_pd       12180 non-null  float64
 63  num_actv_bc_tl              12180 non-null  float64
 64  num_actv_rev_tl             12180 non-null  float64
 65  num_bc_sats                 12180 non-null  float64
 66  num_bc_tl                   12180 non-null  float64
 67  num_il_tl                   12180 non-null  float64
 68  num_op_rev_tl               12180 non-null  float64
 69  num_rev_accts               12180 non-null  float64
 70  num_rev_tl_bal_gt_0         12180 non-null  float64
 71  num_sats                    12180 non-null  float64
 72  num_tl_120dpd_2m            12180 non-null  float64
 73  num_tl_30dpd                12180 non-null  float64
 74  num_tl_90g_dpd_24m          12180 non-null  float64
 75  num_tl_op_past_12m          12180 non-null  float64
 76  pct_tl_nvr_dlq              12180 non-null  float64
 77  percent_bc_gt_75            12180 non-null  float64
 78  pub_rec_bankruptcies        12180 non-null  float64
 79  tax_liens                   12180 non-null  float64
 80  tot_hi_cred_lim             12180 non-null  float64
 81  total_bal_ex_mort           12180 non-null  float64
 82  total_bc_limit              12180 non-null  float64
 83  total_il_high_credit_limit  12180 non-null  float64
 84  hardship_flag               12180 non-null  object
 85  debt_settlement_flag        12180 non-null  object
dtypes: float64(76), int64(2), object(8)
memory usage: 8.0+ MB

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,0,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,0,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,354912,354912,19975.0,0.2565,801.09,28000.0,28.42,0.0,0.0,15.0,...,0,1,0,1,1,0,1,0,1,0
12176,354944,354944,15000.0,0.1774,540.34,50000.0,23.43,4.0,0.0,16.0,...,1,1,0,1,1,0,1,0,1,0
12177,354973,354973,3600.0,0.1862,131.28,60000.0,28.80,0.0,1.0,14.0,...,0,1,0,1,1,0,1,0,1,0
12178,355002,355002,15000.0,0.0881,475.68,62000.0,11.44,0.0,0.0,5.0,...,0,1,0,1,0,1,1,0,1,0
12179,355307,355307,15000.0,0.1774,540.34,54080.0,21.66,1.0,1.0,5.0,...,0,1,1,0,1,0,1,0,1,0

In [14]:
X_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 94 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Unnamed: 0                           12180 non-null  int64
 1   index                                12180 non-null  int64
 2   loan_amnt                            12180 non-null  float64
 3   int_rate                             12180 non-null  float64
 4   installment                          12180 non-null  float64
 5   annual_inc                           12180 non-null  float64
 6   dti                                  12180 non-null  float64
 7   delinq_2yrs                          12180 non-null  float64
 8   inq_last_6mths                       12180 non-null  float64
 9   open_acc                             12180 non-null  float64
 10  pub_rec                              12180 non-null  float64
 11  revol_bal                            12180 non-null  float64
 12  total_acc                            12180 non-null  float64
 13  out_prncp                            12180 non-null  float64
 14  out_prncp_inv                        12180 non-null  float64
 15  total_pymnt                          12180 non-null  float64
 16  total_pymnt_inv                      12180 non-null  float64
 17  total_rec_prncp                      12180 non-null  float64
 18  total_rec_int                        12180 non-null  float64
 19  total_rec_late_fee                   12180 non-null  float64
 20  recoveries                           12180 non-null  float64
 21  collection_recovery_fee              12180 non-null  float64
 22  last_pymnt_amnt                      12180 non-null  float64
 23  collections_12_mths_ex_med           12180 non-null  float64
 24  policy_code                          12180 non-null  float64
 25  acc_now_delinq                       12180 non-null  float64
 26  tot_coll_amt                         12180 non-null  float64
 27  tot_cur_bal                          12180 non-null  float64
 28  open_acc_6m                          12180 non-null  float64
 29  open_act_il                          12180 non-null  float64
 30  open_il_12m                          12180 non-null  float64
 31  open_il_24m                          12180 non-null  float64
 32  mths_since_rcnt_il                   12180 non-null  float64
 33  total_bal_il                         12180 non-null  float64
 34  il_util                              12180 non-null  float64
 35  open_rv_12m                          12180 non-null  float64
 36  open_rv_24m                          12180 non-null  float64
 37  max_bal_bc                           12180 non-null  float64
 38  all_util                             12180 non-null  float64
 39  total_rev_hi_lim                     12180 non-null  float64
 40  inq_fi                               12180 non-null  float64
 41  total_cu_tl                          12180 non-null  float64
 42  inq_last_12m                         12180 non-null  float64
 43  acc_open_past_24mths                 12180 non-null  float64
 44  avg_cur_bal                          12180 non-null  float64
 45  bc_open_to_buy                       12180 non-null  float64
 46  bc_util                              12180 non-null  float64
 47  chargeoff_within_12_mths             12180 non-null  float64
 48  delinq_amnt                          12180 non-null  float64
 49  mo_sin_old_il_acct                   12180 non-null  float64
 50  mo_sin_old_rev_tl_op                 12180 non-null  float64
 51  mo_sin_rcnt_rev_tl_op                12180 non-null  float64
 52  mo_sin_rcnt_tl                       12180 non-null  float64
 53  mort_acc                             12180 non-null  float64
 54  mths_since_recent_bc                 12180 non-null  float64
 55  mths_since_recent_inq                12180 non-null  float64
 56  num_accts_ever_120_pd                12180 non-null  float64
 57  num_actv_bc_tl                       12180 non-null  float64
 58  num_actv_rev_tl                      12180 non-null  float64
 59  num_bc_sats                          12180 non-null  float64
 60  num_bc_tl                            12180 non-null  float64
 61  num_il_tl                            12180 non-null  float64
 62  num_op_rev_tl                        12180 non-null  float64
 63  num_rev_accts                        12180 non-null  float64
 64  num_rev_tl_bal_gt_0                  12180 non-null  float64
 65  num_sats                             12180 non-null  float64
 66  num_tl_120dpd_2m                     12180 non-null  float64
 67  num_tl_30dpd                         12180 non-null  float64
 68  num_tl_90g_dpd_24m                   12180 non-null  float64
 69  num_tl_op_past_12m                   12180 non-null  float64
 70  pct_tl_nvr_dlq                       12180 non-null  float64
 71  percent_bc_gt_75                     12180 non-null  float64
 72  pub_rec_bankruptcies                 12180 non-null  float64
 73  tax_liens                            12180 non-null  float64
 74  tot_hi_cred_lim                      12180 non-null  float64
 75  total_bal_ex_mort                    12180 non-null  float64
 76  total_bc_limit                       12180 non-null  float64
 77  total_il_high_credit_limit           12180 non-null  float64
 78  home_ownership_ANY                   12180 non-null  uint8
 79  home_ownership_MORTGAGE              12180 non-null  uint8
 80  home_ownership_OWN                   12180 non-null  uint8
 81  home_ownership_RENT                  12180 non-null  uint8
 82  verification_status_Not Verified     12180 non-null  uint8
 83  verification_status_Source Verified  12180 non-null  uint8
 84  verification_status_Verified         12180 non-null  uint8
 85  pymnt_plan_n                         12180 non-null  uint8
 86  initial_list_status_f                12180 non-null  uint8
 87  initial_list_status_w                12180 non-null  uint8
 88  application_type_Individual          12180 non-null  uint8
 89  application_type_Joint App           12180 non-null  uint8
 90  hardship_flag_N                      12180 non-null  uint8
 91  hardship_flag_Y                      12180 non-null  uint8
 92  debt_settlement_flag_N               12180 non-null  uint8
 93  debt_settlement_flag_Y               12180 non-null  uint8
dtypes: float64(76), int64(2), uint8(16)
memory usage: 7.4 MB

In [15]:
y_train = train_df["loan_status"]
y_train

0         low_risk
1         low_risk
2         low_risk
3         low_risk
4         low_risk
           ...
12175    high_risk
12176    high_risk
12177    high_risk
12178    high_risk
12179    high_risk
Name: loan_status, Length: 12180, dtype: object

In [16]:
# Convert categorical data to numeric and separate target feature for testing data
X_test_df = pd.get_dummies(test_df.drop(columns=["loan_status"]))
X_test_df

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,67991,67991,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,...,0,0,1,0,1,1,0,1,0,1
1,25429,25429,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,...,0,0,1,0,1,1,0,1,0,1
2,38496,38496,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,...,0,0,1,0,1,1,0,1,0,1
3,19667,19667,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,...,0,0,1,0,1,1,0,1,0,1
4,37505,37505,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,...,0,0,1,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,77282,77282,30000.0,0.1240,673.42,140480.0,15.74,0.0,0.0,20.0,...,1,0,1,1,0,1,0,1,0,1
4698,77291,77291,24000.0,0.0756,747.22,50000.0,26.81,0.0,0.0,9.0,...,0,0,1,0,1,1,0,1,0,1
4699,77292,77292,10000.0,0.2305,387.36,33000.0,38.51,0.0,2.0,7.0,...,0,1,1,1,0,1,0,1,0,1
4700,77297,77297,8000.0,0.1862,205.86,38000.0,16.36,0.0,1.0,8.0,...,1,0,1,0,1,1,0,1,0,1
4701,77304,77304,30000.0,0.2055,1123.34,180000.0,12.06,0.0,0.0,8.0,...,1,0,1,1,0,1,0,1,0,1

In [28]:
y_test = test_df["loan_status"]
y_test

0        low_risk
1        low_risk
2        low_risk
3        low_risk
4        low_risk
          ...
4697    high_risk
4698    high_risk
4699    high_risk
4700    high_risk
4701    high_risk
Name: loan_status, Length: 4702, dtype: object

In [17]:
X_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 93 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Unnamed: 0                           4702 non-null   int64
 1   index                                4702 non-null   int64
 2   loan_amnt                            4702 non-null   float64
 3   int_rate                             4702 non-null   float64
 4   installment                          4702 non-null   float64
 5   annual_inc                           4702 non-null   float64
 6   dti                                  4702 non-null   float64
 7   delinq_2yrs                          4702 non-null   float64
 8   inq_last_6mths                       4702 non-null   float64
 9   open_acc                             4702 non-null   float64
 10  pub_rec                              4702 non-null   float64
 11  revol_bal                            4702 non-null   float64
 12  total_acc                            4702 non-null   float64
 13  out_prncp                            4702 non-null   float64
 14  out_prncp_inv                        4702 non-null   float64
 15  total_pymnt                          4702 non-null   float64
 16  total_pymnt_inv                      4702 non-null   float64
 17  total_rec_prncp                      4702 non-null   float64
 18  total_rec_int                        4702 non-null   float64
 19  total_rec_late_fee                   4702 non-null   float64
 20  recoveries                           4702 non-null   float64
 21  collection_recovery_fee              4702 non-null   float64
 22  last_pymnt_amnt                      4702 non-null   float64
 23  collections_12_mths_ex_med           4702 non-null   float64
 24  policy_code                          4702 non-null   float64
 25  acc_now_delinq                       4702 non-null   float64
 26  tot_coll_amt                         4702 non-null   float64
 27  tot_cur_bal                          4702 non-null   float64
 28  open_acc_6m                          4702 non-null   float64
 29  open_act_il                          4702 non-null   float64
 30  open_il_12m                          4702 non-null   float64
 31  open_il_24m                          4702 non-null   float64
 32  mths_since_rcnt_il                   4702 non-null   float64
 33  total_bal_il                         4702 non-null   float64
 34  il_util                              4702 non-null   float64
 35  open_rv_12m                          4702 non-null   float64
 36  open_rv_24m                          4702 non-null   float64
 37  max_bal_bc                           4702 non-null   float64
 38  all_util                             4702 non-null   float64
 39  total_rev_hi_lim                     4702 non-null   float64
 40  inq_fi                               4702 non-null   float64
 41  total_cu_tl                          4702 non-null   float64
 42  inq_last_12m                         4702 non-null   float64
 43  acc_open_past_24mths                 4702 non-null   float64
 44  avg_cur_bal                          4702 non-null   float64
 45  bc_open_to_buy                       4702 non-null   float64
 46  bc_util                              4702 non-null   float64
 47  chargeoff_within_12_mths             4702 non-null   float64
 48  delinq_amnt                          4702 non-null   float64
 49  mo_sin_old_il_acct                   4702 non-null   float64
 50  mo_sin_old_rev_tl_op                 4702 non-null   float64
 51  mo_sin_rcnt_rev_tl_op                4702 non-null   float64
 52  mo_sin_rcnt_tl                       4702 non-null   float64
 53  mort_acc                             4702 non-null   float64
 54  mths_since_recent_bc                 4702 non-null   float64
 55  mths_since_recent_inq                4702 non-null   float64
 56  num_accts_ever_120_pd                4702 non-null   float64
 57  num_actv_bc_tl                       4702 non-null   float64
 58  num_actv_rev_tl                      4702 non-null   float64
 59  num_bc_sats                          4702 non-null   float64
 60  num_bc_tl                            4702 non-null   float64
 61  num_il_tl                            4702 non-null   float64
 62  num_op_rev_tl                        4702 non-null   float64
 63  num_rev_accts                        4702 non-null   float64
 64  num_rev_tl_bal_gt_0                  4702 non-null   float64
 65  num_sats                             4702 non-null   float64
 66  num_tl_120dpd_2m                     4702 non-null   float64
 67  num_tl_30dpd                         4702 non-null   float64
 68  num_tl_90g_dpd_24m                   4702 non-null   float64
 69  num_tl_op_past_12m                   4702 non-null   float64
 70  pct_tl_nvr_dlq                       4702 non-null   float64
 71  percent_bc_gt_75                     4702 non-null   float64
 72  pub_rec_bankruptcies                 4702 non-null   float64
 73  tax_liens                            4702 non-null   float64
 74  tot_hi_cred_lim                      4702 non-null   float64
 75  total_bal_ex_mort                    4702 non-null   float64
 76  total_bc_limit                       4702 non-null   float64
 77  total_il_high_credit_limit           4702 non-null   float64
 78  home_ownership_ANY                   4702 non-null   uint8
 79  home_ownership_MORTGAGE              4702 non-null   uint8
 80  home_ownership_OWN                   4702 non-null   uint8
 81  home_ownership_RENT                  4702 non-null   uint8
 82  verification_status_Not Verified     4702 non-null   uint8
 83  verification_status_Source Verified  4702 non-null   uint8
 84  verification_status_Verified         4702 non-null   uint8
 85  pymnt_plan_n                         4702 non-null   uint8
 86  initial_list_status_f                4702 non-null   uint8
 87  initial_list_status_w                4702 non-null   uint8
 88  application_type_Individual          4702 non-null   uint8
 89  application_type_Joint App           4702 non-null   uint8
 90  hardship_flag_N                      4702 non-null   uint8
 91  hardship_flag_Y                      4702 non-null   uint8
 92  debt_settlement_flag_N               4702 non-null   uint8
dtypes: float64(76), int64(2), uint8(15)
memory usage: 2.9 MB

In [18]:
X_train_df.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N',
       'debt_settlement_flag_Y'],
      dtype='object')

In [19]:
# add missing dummy variables to testing set
for column in X_train_df.columns:
    if column not in X_test_df.columns:
        X_test_df[column] = 0

In [21]:
X_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 94 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Unnamed: 0                           4702 non-null   int64
 1   index                                4702 non-null   int64
 2   loan_amnt                            4702 non-null   float64
 3   int_rate                             4702 non-null   float64
 4   installment                          4702 non-null   float64
 5   annual_inc                           4702 non-null   float64
 6   dti                                  4702 non-null   float64
 7   delinq_2yrs                          4702 non-null   float64
 8   inq_last_6mths                       4702 non-null   float64
 9   open_acc                             4702 non-null   float64
 10  pub_rec                              4702 non-null   float64
 11  revol_bal                            4702 non-null   float64
 12  total_acc                            4702 non-null   float64
 13  out_prncp                            4702 non-null   float64
 14  out_prncp_inv                        4702 non-null   float64
 15  total_pymnt                          4702 non-null   float64
 16  total_pymnt_inv                      4702 non-null   float64
 17  total_rec_prncp                      4702 non-null   float64
 18  total_rec_int                        4702 non-null   float64
 19  total_rec_late_fee                   4702 non-null   float64
 20  recoveries                           4702 non-null   float64
 21  collection_recovery_fee              4702 non-null   float64
 22  last_pymnt_amnt                      4702 non-null   float64
 23  collections_12_mths_ex_med           4702 non-null   float64
 24  policy_code                          4702 non-null   float64
 25  acc_now_delinq                       4702 non-null   float64
 26  tot_coll_amt                         4702 non-null   float64
 27  tot_cur_bal                          4702 non-null   float64
 28  open_acc_6m                          4702 non-null   float64
 29  open_act_il                          4702 non-null   float64
 30  open_il_12m                          4702 non-null   float64
 31  open_il_24m                          4702 non-null   float64
 32  mths_since_rcnt_il                   4702 non-null   float64
 33  total_bal_il                         4702 non-null   float64
 34  il_util                              4702 non-null   float64
 35  open_rv_12m                          4702 non-null   float64
 36  open_rv_24m                          4702 non-null   float64
 37  max_bal_bc                           4702 non-null   float64
 38  all_util                             4702 non-null   float64
 39  total_rev_hi_lim                     4702 non-null   float64
 40  inq_fi                               4702 non-null   float64
 41  total_cu_tl                          4702 non-null   float64
 42  inq_last_12m                         4702 non-null   float64
 43  acc_open_past_24mths                 4702 non-null   float64
 44  avg_cur_bal                          4702 non-null   float64
 45  bc_open_to_buy                       4702 non-null   float64
 46  bc_util                              4702 non-null   float64
 47  chargeoff_within_12_mths             4702 non-null   float64
 48  delinq_amnt                          4702 non-null   float64
 49  mo_sin_old_il_acct                   4702 non-null   float64
 50  mo_sin_old_rev_tl_op                 4702 non-null   float64
 51  mo_sin_rcnt_rev_tl_op                4702 non-null   float64
 52  mo_sin_rcnt_tl                       4702 non-null   float64
 53  mort_acc                             4702 non-null   float64
 54  mths_since_recent_bc                 4702 non-null   float64
 55  mths_since_recent_inq                4702 non-null   float64
 56  num_accts_ever_120_pd                4702 non-null   float64
 57  num_actv_bc_tl                       4702 non-null   float64
 58  num_actv_rev_tl                      4702 non-null   float64
 59  num_bc_sats                          4702 non-null   float64
 60  num_bc_tl                            4702 non-null   float64
 61  num_il_tl                            4702 non-null   float64
 62  num_op_rev_tl                        4702 non-null   float64
 63  num_rev_accts                        4702 non-null   float64
 64  num_rev_tl_bal_gt_0                  4702 non-null   float64
 65  num_sats                             4702 non-null   float64
 66  num_tl_120dpd_2m                     4702 non-null   float64
 67  num_tl_30dpd                         4702 non-null   float64
 68  num_tl_90g_dpd_24m                   4702 non-null   float64
 69  num_tl_op_past_12m                   4702 non-null   float64
 70  pct_tl_nvr_dlq                       4702 non-null   float64
 71  percent_bc_gt_75                     4702 non-null   float64
 72  pub_rec_bankruptcies                 4702 non-null   float64
 73  tax_liens                            4702 non-null   float64
 74  tot_hi_cred_lim                      4702 non-null   float64
 75  total_bal_ex_mort                    4702 non-null   float64
 76  total_bc_limit                       4702 non-null   float64
 77  total_il_high_credit_limit           4702 non-null   float64
 78  home_ownership_ANY                   4702 non-null   uint8
 79  home_ownership_MORTGAGE              4702 non-null   uint8
 80  home_ownership_OWN                   4702 non-null   uint8
 81  home_ownership_RENT                  4702 non-null   uint8
 82  verification_status_Not Verified     4702 non-null   uint8
 83  verification_status_Source Verified  4702 non-null   uint8
 84  verification_status_Verified         4702 non-null   uint8
 85  pymnt_plan_n                         4702 non-null   uint8
 86  initial_list_status_f                4702 non-null   uint8
 87  initial_list_status_w                4702 non-null   uint8
 88  application_type_Individual          4702 non-null   uint8
 89  application_type_Joint App           4702 non-null   uint8
 90  hardship_flag_N                      4702 non-null   uint8
 91  hardship_flag_Y                      4702 non-null   uint8
 92  debt_settlement_flag_N               4702 non-null   uint8
 93  debt_settlement_flag_Y               4702 non-null   int64
dtypes: float64(76), int64(3), uint8(15)
memory usage: 2.9 MB

In [29]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=3)
classifier

classifier.fit(X_train_df, y_train)

classifier.score(X_test_df, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5253083794130158

In [31]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=3)
classifier.fit(X_train_df, y_train)
classifier.score(X_test_df, y_test)

0.5814547001276053

In [ ]:
# Scale the data

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score